apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
metadata:
  name: kustomize-node-oom-tester
images:
- name: armujahid/node-oom-tester
  newTag: "0.0.1"
resources:
- ../../base
