apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomize-node-oom-tester
resources:
- deployment.yaml
configMapGenerator:
- name: node-oom-tester
  envs:
  - application.properties
